* Css-Comb
A wrapper for using [[https://github.com/csscomb/csscomb.js][csscomb.js]] from within emacs. Allows you to comb region/buffers
** Install
*** Install csscomb
You'll need to first install `csscomb` using npm

#+BEGIN_SRC sh
[sudo] npm install -g csscomb
#+END_SRC
*** Install this package
Until I add this package to melpa, you can manually install it.
- Clone this package somewhere on your computer
- Add the cloned dir to your load-path
- `require(css-comb)` in your init.el

You can now use this package by calling `M-x css-comb`. It'll comb the region if selected or the whole buffer.
You should probably add a shortcut for calling `css-comb` in the css-buffers.
#+begin_src emacs-lisp :tangle yes
(after-load 'css-mode
  (define-key css-mode-map (kbd "C-c C-x c") 'css-comb))
#+end_src
** Protip
You should also install [[https://github.com/yasuyk/web-beautify][web-beautify]] package. The CSS generated by csscomb.js is horrible, this package utilize web-beautify if present to make it look better. You should use web-beautify anyway, even if you don't use css-comb
